port: 8000

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 86400

mongo:
  production_database: "mongodb+srv://admin:wqDohhdGEHR2lI6O@cluster0.s8igoep.mongodb.net/"
  development_database: "mongodb://localhost:27017/"
  name: "testdb"
  normal_user_collection: "normal_users"
  business_user_collection: "business_users"
  job_collection: "jobs"
  region_collection: "regions"
  city_collection: "cities"
  district_collection: "districts"
  profession_collection : "professions"
